apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatgpt-mattermost-bot.fullname" . }}-secret
  labels:
    app: chatgpt-mattermost-bot
  {{- include "chatgpt-mattermost-bot.labels" . | nindent 4 }}
data:
  MATTERMOST_TOKEN: {{ .Values.chatbot.mattermostToken | b64enc }}
  OPENAI_API_KEY: {{ .Values.chatbot.openaiApiKey | b64enc }}